resolver: lts-18.16
packages:
- .
extra-deps:
- 'amazonka-1.6.1'
- 'cairo-0.13.8.1'
- 'digestive-functors-0.8.4.2'
- 'digestive-functors-blaze-0.6.2.0'
- 'eventful-dynamodb-0.2.0'
- 'gtk2hs-buildtools-0.13.8.2'
- 'hal-1.0.0.1'
- 'unliftio-core-0.1.2.0'
- 'urlencoded-0.5.0.0'
- 'wai-handler-hal-0.3.0.0'
- git: https://github.com/fmthoma/svgcairo
  commit: fd25143acd56e9a2c5af9eea3774dac7fe3936c1
- Cabal-3.0.2.0
- glib-0.13.8.1
nix:
  packages:
  - 'zlib'
  - 'pkgconfig'
  - 'librsvg'
