resolver: lts-17.9
packages:
- .
extra-deps:
- 'amazonka-1.6.1'
- 'digestive-functors-0.8.4.2'
- 'digestive-functors-blaze-0.6.2.0'
- 'eventful-dynamodb-0.2.0'
- 'qrcode-0.1.2'
- 'unliftio-core-0.1.2.0'
- git: 'https://github.com/jaspervdj/urlencoded.git'
  commit: '79e31ed9279c820bb89e36824464fdfb4b7b968a'
nix:
  packages:
  - 'zlib'
